### PR TITLE
fix: return class_name + ( import_path ) as class_name

### PR DESCRIPTION
**Pull request by zsinnema**
# 403
https://github.com/MetaCell/geppetto-scidash/issues/403

## Changes
Test creation view - some test classes have the same name but different import path

### CODE REVIEW

**Comment by zsinnema** [comment]
Is this what you have in mind?

**Comment by gidili** [comment]
@zsinnema this might do the trick for that issue! 

Does this also mean that every time we are fetching the class name now we have this version with the path everywhere class name is displayed (many of the grids and detailed views)? If so, it might be an unwanted consequence of the fix.

**Comment by zsinnema** [comment]
@gidili yes that's the side effect of it. I was doubting to add an extra field in the serializer or replace the class_name value. I have tested a little bit with long import paths and it does show surprisingly good (also in the popups/dialogs)

**Comment by gidili** [comment]
@zsinnema ok, that sounds good, maybe post a screenshot so we can get @rgerkin's feedback too! 

We can always go back and add the extra field.

**Review by ddelpiano — APPROVED** [review]

**Pull request merged**
