### PR TITLE
script to install scidash 

### PR DESCRIPTION
**Pull request by rodriguez-facundo**
# create script to install scidash
https://trello.com/c/9Jkl27NX/242-create-script-to-install-scidash

## Changes
add script to install scidash 

## Related issues
this closes https://github.com/MetaCell/scidash/issues/48

### CODE REVIEW

**Comment by gidili** [comment]
@NeZanyat can you also review?

**Comment by NeZanyat** [comment]
Hi everyone, thanks for work on this script, it looks really nice, but I was planning to move all service things like this into one Makefile, it will be more unified. That's why I can't merge this PR right now, but I'll take some useful things from this PR and will put them into Makefile

**Comment by rodriguez-facundo** [comment]
sure, no problem @NeZanyat . Should I close this PR or you will?

**Comment by NeZanyat** [comment]
Leave it as for now, I'll close it in future

**Pull request merged**
