### PR TITLE
Feature/393

### PR DESCRIPTION
**Pull request by ddelpiano**
- Dockerfile-postgres modified to inject data by default in the database
- Dockerfile-virgo modified to reduce the footprint by the data and take into account the branch we should build (we need to modify this slightly when we will align scidash with the latest version of geppetto, this means changing all the branches used by the copy.sh script, at the moment I am using alpha and simflag tags).
- Dockerfile-scidash modified to split virgo by the python backend (thx @zsinnema), install backend and frontend makefile and scripts now modified to build the branch passed by the travis build.
- .travis.yml added
- trigger-travis.sh added and configured to trigger python unit tests (for now it's a simple echo that needs to be replaced in the travis file when these will be ready) ad then trigger the other build on geppetto-scidash providing the branch from here. 
- other improvements brought from @zsinnema branch with feature/400.

### CODE REVIEW

**Comment by ddelpiano** [comment]
@gidili could you enable travis on this https://travis-ci.org/MetaCell/geppetto-scidash and this https://travis-ci.org/MetaCell/scidash please ? Thx!

**Comment by jrmartin** [comment]
I started the build in travis for branch feature/393, it's failing now on docker-virgo. 
https://travis-ci.org/metacell/geppetto-scidash/builds/626453282

**Comment by zsinnema** [comment]
I will see what's wrong and try to fix it

**Comment by zsinnema** [comment]
@jrmartin @ddelpiano the issue is that feature/399 from geppetto-scidash uses the development branch of scidash but the feature/393 (split the docker images) isn't in the development branch yet. During the work to split the docker images I also encountered the problem (the build can't download openjdk 8 anymore). I fixed it in the feature/400 which is merged into feature/393. 
So to fix this we should merge feature/393 into development.

**Comment by ddelpiano** [comment]
> @jrmartin @ddelpiano the issue is that feature/399 from geppetto-scidash uses the development branch of scidash but the feature/393 (split the docker images) isn't in the development branch yet. During the work to split the docker images I also encountered the problem (the build can't download openjdk 8 anymore). I fixed it in the feature/400 which is merged into feature/393.
> So to fix this we should merge feature/393 into development.

@zsinnema @jrmartin I fixed this within the branch itself, it should work now (just run the last build to double check).

**Pull request merged**
